BookManagement/BookManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title='Book Management API',
        default_version='v1',
        description='The API for book management application',
        terms_of_service='https://www.google.com/policies/terms/',
        contact=openapi.Contact(email='support@example.com')
    ),
    public=True,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('authentication.urls', namespace='authentication')),
    path('api/', include('api.urls', namespace='api')),
    path('docs/', schema_view.with_ui('swagger',
         cache_timeout=0), name='schema-swagger'),
    path('docs-redoc/', schema_view.with_ui('redoc',
         cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BookManagement/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.BookListAPIView.as_view(), name='book_list'),
    path('book/add/', views.AddBookAPIView.as_view(), name='add_book'),
    path('book/update/<int:pk>/',
         views.UpdateBookAPIView.as_view(), name='update_book'),
    path('book/delete/<int:pk>/',
         views.DeleteBookAPIView.as_view(), name='delete_book'),
]

BookManagement/authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('password-change/', views.UserPasswordChangeView.as_view(),
         name='password_change'),
    path('password_reset/', views.UserPasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>/',
         views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

BookManagement/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body data-bs-theme="dark">

  {% include 'navbar.html' %}

  <div class="container mt-4">
    {% if messages %}
      {% for message in messages %}
          {% if "success" in message.tags %}
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
          {% elif "error" in message.tags %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
          {% endif %}
      {% endfor %}
    {% endif %}


    {% block content %}
    {% endblock %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

BookManagement/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <a class="navbar-brand fw-bold" href="{% url 'core:book_list' %}">📚 Books</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if perms.core.delete_book %}
            <li class="nav-item">
              <a class="btn btn-success ms-2" href="{% url 'core:add_book' %}">➕ Add Book</a>
            </li>
          {% endif %}
        </ul>

        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="🔍 Search by title" name="search_by_title">
          <input class="form-control me-2" type="search" placeholder="🔍 Search by genre" name="search_by_genre">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        <ul class="navbar-nav ms-3 ms-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-light fw-bold" href="#" id="userDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                👤 {{ user }}
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                <li><a class="dropdown-item" href="{% url 'authentication:password_change' %}">🔑 Change Password</a></li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <form action="{% url 'authentication:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="dropdown-item text-danger">🚪 Logout</button>
                  </form>
                </li>
              </ul>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="btn btn-outline-success" href="{% url 'authentication:login' %}">🔑 Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
  </div>
</nav>