BookManagement/BookManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title='Book Management API',
        default_version='v1',
        description='The API for book management application',
        terms_of_service='https://www.google.com/policies/terms/',
        contact=openapi.Contact(email='support@example.com')
    ),
    public=True,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('authentication.urls', namespace='authentication')),
    path('api/', include('api.urls', namespace='api')),
    path('docs/', schema_view.with_ui('swagger',
         cache_timeout=0), name='schema-swagger'),
    path('docs-redoc/', schema_view.with_ui('redoc',
         cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BookManagement/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.BookListAPIView.as_view(), name='book_list'),
    path('book/add/', views.AddBookAPIView.as_view(), name='add_book'),
    path('book/update/<int:pk>/',
         views.UpdateBookAPIView.as_view(), name='update_book'),
    path('book/delete/<int:pk>/',
         views.DeleteBookAPIView.as_view(), name='delete_book'),
]

BookManagement/authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('password-change/', views.UserPasswordChangeView.as_view(),
         name='password_change'),
    path('password_reset/', views.UserPasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>/',
         views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

BookManagement/authentication/models.py
from django.db import models

# Create your models here.

BookManagement/authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

BookManagement/authentication/views.py
from .forms import RegistrationForm
from django.contrib.auth.models import User
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView, PasswordResetConfirmView


class RegistrationView(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = 'authentication/registration.html'
    success_url = reverse_lazy('authentication:login')


class UserLoginView(LoginView):
    template_name = 'authentication/login.html'


class UserLogoutView(LogoutView):
    next_page = reverse_lazy('core:book_list')


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'authentication/change_password.html'
    success_url = reverse_lazy('core:book_list')


class UserPasswordResetView(PasswordResetView):
    template_name = 'authentication/password_reset_request.html'
    email_template_name = 'authentication/password_reset_emai.html'
    success_url = reverse_lazy('core:book_list')


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'password_reset_confirm.html'
    success_url = reverse_lazy('authentication:login')

BookManagement/authentication/templates/authentication/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Change Password {% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 80vh;">
    <div class="card shadow-lg p-4 border-0 rounded" style="width: 380px;">
        <h2 class="text-center text-primary">Change Password</h2>

        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}

            <div class="d-grid gap-2 mt-3">
                <button type="submit" class="btn btn-success">Change</button>
                <a href="{% url 'core:book_list' %}" class="btn btn-outline-danger">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

BookManagement/authentication/templates/authentication/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Login {% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 80vh;">
    <div class="card shadow-lg p-4 border-0 rounded" style="width: 380px;">
        <h2 class="text-center text-primary">Login</h2>

        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}

            <div class="d-grid gap-2 mt-3">
                <button type="submit" class="btn btn-success">Login</button>
                <a href="{% url 'core:book_list' %}" class="btn btn-outline-danger">Cancel</a>
            </div>
        </form>

        <div class="text-center mt-3">
            <a href="{% url 'authentication:password_reset' %}" class="text-decoration-none fw-bold text-warning">
                🔁 Forgot Password?
            </a>
        </div>

        <div class="text-center mt-3">
            <p class="mb-0">Don't have an account?</p>
            <a href="{% url 'authentication:registration' %}" class="text-decoration-none fw-bold text-primary">Register here</a>
        </div>
    </div>
</div>
{% endblock %}

BookManagement/authentication/templates/authentication/password_reset_email.html
<h1> Password Reset Request </h1>
<p>Hello</p>
<p>You requested a password reset for your account, please click the button to finish the process</p>
<a class="btn btn-success" href="{{ protocol }}://{{ domain }}/password_reset_confirm/{{ uid }}/{{ token }}/">
  Reset Password
</a>

BookManagement/authentication/templates/authentication/password_reset_request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Reset Password {% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 80vh;">
    <div class="card shadow-lg p-4 border-0 rounded" style="width: 380px;">
        <h2 class="text-center text-primary">Reset Password</h2>
        <p class="text-center text-muted">Enter your email to receive password reset instructions.</p>
         <form method="post">
            {% csrf_token %}
            {{ form|crispy }}

            <div class="d-grid gap-2 mt-3">
                <button type="submit" class="btn btn-success">Send Reset Link</button>
                <a href="{% url 'core:book_list' %}" class="btn btn-outline-danger">Cancel</a>
            </div>
        </form>

        <div class="text-center mt-3">
            <p class="mb-0">Remember your password?</p>
            <a href="{% url 'authentication:login' %}" class="text-decoration-none fw-bold text-primary">Login here</a>
        </div>
    </div>
</div>
{% endblock %}

BookManagement/authentication/templates/authentication/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Registration {% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 80vh;">
    <div class="card shadow-lg p-4 border-0 rounded" style="width: 400px; max-width: 90%;">
        <h2 class="text-center text-primary mb-3">Registration</h2>

        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}

            <div class="d-grid gap-2 mt-3">
                <button type="submit" class="btn btn-success">Register</button>
                <a href="{% url 'core:book_list' %}" class="btn btn-outline-danger">Cancel</a>
            </div>
        </form>

        <div class="text-center mt-3">
            <p class="mb-0">Already have an account?</p>
            <a href="{% url 'authentication:login' %}" class="text-decoration-none fw-bold text-primary">Login here</a>
        </div>
    </div>
</div>
{% endblock %}